Repository K-Bulkup/Frontend, pull requests merged in 2025-08, with the labels that each got.

#50 [Refactor] #49 : 로그인,회원가입 화면 통일화
  src/components/common/BaseSelectRole.vue
  src/composables/user/useSignup.js
  src/views/auth/LoginPage.vue
  src/views/auth/SignupPage.vue
Labels: 🛠Refactor

#47 [Feature] #19 : 트레이너 마이페이지 수정
  src/assets/images/trainer/mypage/certificationIcon.svg
  src/assets/images/trainer/mypage/memberIcon.svg
  src/assets/images/trainer/mypage/qnaIcon.svg
  src/components/trainer/mypage/TrainerGreeting.vue
  src/components/trainer/mypage/TrainerInfo.vue
  src/components/trainer/mypage/TrainerMenu.vue
Labels: ✨New Feature

#48 [Refactor] #46 : 자산 메인 페이지 수정하기
  src/components/assetCharts/CompositionDonutChart.vue
  src/components/assetCharts/WithdrawalDonutChart.vue
  src/components/common/ConnectSuccessModal.vue
  src/composables/api/useAssetApi.js
  src/composables/asset/useCreateAsset.js
  src/composables/asset/useFetchAsset.js
  src/views/trainee/asset/AccountConnectPage.vue
  src/views/trainee/asset/AssetMainPage.vue
Labels: 🛠Refactor

#59 [Fix] #58 : 로그인 상태 유지 및 토큰 이슈
  src/main.js
  src/router/index.js
Labels: 🐞Bug Fix

#55 [Feature] # 43 : 트레이닝/루틴 UI 개선 및 기능 수정
  src/components/trainee/training/RoutineVideo.vue
  src/components/trainer/training/TrainerRoutineAddModal.vue
  src/views/trainee/TraineeRoutineDetailPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
  src/views/trainer/TrainerTrainingInputPage.vue
  src/views/trainer/TrainerTrainingPage.vue
Labels: 🛠Refactor, ✨New Feature

#64 [Feature] : 트레이니 트레이닝 리뷰
  src/components/common/BaseTextarea.vue
  src/composables/api/trainee/mypage/traineeReviewApi.js
  src/composables/review/useCreateReview.js
  src/composables/review/useFetchReview.js
  src/router/index.js
  src/views/trainee/TraineeReviewPage.vue
Labels: ✨New Feature

#62 [Feature] #61 : 결제 전 트레이닝 상세 페이지 구현
  src/views/training/TrainingDetailPage.vue
Labels: ✨New Feature

#69 [Feature] #44 : 트레이니, 트레이너 자산 정보 전송 & 다운로드 기능
  src/components/chat/ChatHeader.vue
  src/components/chat/ChatInput.vue
  src/composables/api/useAiChatApi.js
  src/composables/api/useAssetApi.js
  src/router/index.js
  src/views/chat/PtChatPage.vue
  src/views/trainee/asset/AssetAiChatPage.vue
Labels: ✨New Feature

#68 [Refactor] : API 호출 Prefix 이용하기
  src/composables/api/trainee/mypage/traineeReviewApi.js
  src/composables/api/useAssetApi.js
  src/views/trainee/asset/AccountConnectPage.vue
Labels: 🛠Refactor

#76 [Feature] #74 : 트레이니 마이페이지 개발
  src/assets/images/mascot/keumyook.png
  src/components/trainee/mypage/CourseList.vue
  src/components/trainee/mypage/ProfileCard.vue
  src/composables/api/trainee/mypage/traineeTrainingApi.js
  src/views/trainee/TraineeMyPage.vue
Labels: ✨New Feature

#80 [Feature] #79 : 홈화면 주소 변경
  src/router/index.js
Labels: ✨New Feature

#91 [Feature] #82 : 채팅방 생성/이동 및 프로필 이미지 적용 기능 구현
  src/views/chat/PtChatPage.vue
Labels: ✨New Feature

#95 [Fix] #94 : 트레이닝 등록 키 관련 오류 수정
  src/components/common/BaseFormField.vue
  src/components/trainer/training/TrainerRoutineAddModal.vue
  src/components/trainer/training/TrainerRoutineSection.vue
  src/components/trainer/training/TrainingStep2Curriculum.vue
  src/views/trainer/TrainerTrainingInputPage.vue
Labels: 🐞Bug Fix

#103 [Fix] : 리뷰 작성 완료 시 리뷰 버튼 비활성화
  src/composables/api/trainee/training/traineeTrainingDetailAPI.js
  src/views/trainee/TraineeTrainingDetailPage.vue
Labels: 🛠Refactor, 🐞Bug Fix

#108 [Feature] #106 : 리뷰 API 연동 및 루틴 답안 변수명 수정
  src/components/trainer/training/TrainerRoutineAddModal.vue
  src/components/trainer/training/TrainingStep1Category.vue
  src/composables/api/useReviewApi.js
  src/views/trainer/TrainerTrainingDetailPage.vue
  src/views/trainer/TrainerTrainingInputPage.vue
Labels: 🐞Bug Fix, ✨New Feature

#113 Feat : 트레이너 트레이닝 목록 조회 API 연동
  src/composables/api/trainer/training/trainerTrainingAPI.js
  src/views/trainer/TrainerTrainingPage.vue
Labels: ✨New Feature

#118 [Featrue] : 트레이너 트레이닝 Q&A 답변
  src/components/trainer/mypage/TrainerMenu.vue
  src/composables/api/useQnAAnswer.js
  src/router/index.js
  src/views/trainee/TraineeQnAPage.vue
  src/views/trainer/TrainerTrainingQnAPage.vue
Labels: ✨New Feature

#119 [Feature] #112 : 트레이너 프로필 기본 이미지 추가 및 루틴 영상 없을 때 숨기기
  src/components/trainee/training/RoutineVideo.vue
  src/views/trainer/TrainerTrainingDetailPage.vue
  src/views/training/TrainingDetailPage.vue
Labels: ✨New Feature

#121 [Feature] #120 : 트레이너가 확인하는 트레이닝 상세 페이지 구현
  src/composables/api/trainer/training/trainerTrainingDetailApi.js
  src/views/trainer/TrainerTrainingDetailPage.vue
Labels: ✨New Feature

#129 [Fix] : Q&A 버그 해결
  src/components/trainer/mypage/TrainerMenu.vue
  src/views/trainee/TraineeQnAPage.vue
  src/views/trainee/TraineeTrainingQuestionInput.vue
  src/views/trainee/asset/AccountConnectPage.vue
  src/views/trainer/TrainerTrainingQnAPage.vue
Labels: 🐞Bug Fix

#136 [Refactor] #122: 트레이너 수강생 증가 로직 화면 수정
  src/composables/api/trainee/training/routineDetailAPI.js
  src/composables/api/trainee/training/traineeTrainingDetailAPI.js
  src/stores/routineLock.js
  src/views/trainee/TraineeRoutineDetailPage.vue
  src/views/trainee/TraineeTrainerDetailPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
  src/views/trainer/TrainerTrainingDetailPage.vue
  src/views/training/TrainingDetailPage.vue
Labels: 🛠Refactor, ✨New Feature

#135 [Feat] : 자산 불러오기 기능 추가
  src/composables/api/useAssetApi.js
  src/views/trainee/TraineeQnAPage.vue
  src/views/trainee/asset/AssetMainPage.vue
  src/views/trainer/TrainerTrainingQnAPage.vue
Labels: ✨New Feature

#141 [Feature] : AI 컨설팅 자산 데이터 응답 개선 및 트레이닝 상태 조회 로직 추가
  src/components/chat/ChatBubble.vue
  src/composables/api/trainee/training/traineeTrainingDetailAPI.js
  src/views/trainee/TraineeTrainingDetailPage.vue
  src/views/trainee/asset/AssetAiChatPage.vue
Labels: ✨New Feature

#144 [Refactor] : 실천형 루틴
  src/composables/api/trainee/training/routineResultAPI.js
  src/views/trainee/TraineeRoutineDetailPage.vue
Labels: 🛠Refactor

#151 [Refactor] #138 : 트레이너 홈 화면 리팩토링
  src/App.vue
  src/assets/images/arrow-back.png
  src/assets/images/arrow-back.svg
  src/assets/images/mascot/logo.png
  src/assets/images/trainer/mypage/badge.png
  src/assets/images/trainer/mypage/edit.png
  src/assets/images/trainer/mypage/profile.png
  src/assets/images/trainer/mypage/trainerCareerModify.svg
  src/components/common/BaseHeader.vue
  src/components/layout/NavigationBar.vue
  src/components/trainee/training/TrainingCard.vue
  src/components/trainee/training/home/TrainingCard.vue
  src/components/trainer/mypage/HeaderWithLogo.vue
  src/components/trainer/mypage/TrainerCareer.vue
  src/components/trainer/mypage/TrainerGreeting.vue
  src/components/trainer/mypage/TrainerInfo.vue
  src/views/auth/LoginPage.vue
  src/views/trainer/TrainerMyPage.vue
  src/views/trainer/TrainerTrainingPage.vue
  src/views/training/TrainingListPage.vue
  tailwind.config.js
Labels: 🛠Refactor

#152 [Refactor] #146 : 트레이닝 결제 후 상세 페이지 디자인 변경
  src/assets/images/plus_green.svg
  src/components/common/ProgressBar.vue
  src/components/trainee/training/RoutineTypeOX.vue
  src/components/trainee/training/RoutineTypePractice.vue
  src/components/trainee/training/RoutineTypeSubjective.vue
  src/components/trainee/training/RoutineVideo.vue
  src/components/trainee/training/TraineeRoutineSection.vue
  src/views/trainee/TraineeRoutineDetailPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
Labels: 🛠Refactor

#158 [Fix] #138 : 트레이닝 상태 컬럼명 수정
  src/App.vue
  src/views/trainer/TrainerTrainingPage.vue
Labels: 🐞Bug Fix

#162 [Refactor] #161 : 수익관리 페이지 디자인적인 수정
  src/assets/images/trainer/mypage/coins.svg
  src/components/assetCharts/BalanceLineChart.vue
  src/components/layout/NavigationBar.vue
  src/views/trainer/TrainerReportPage.vue
Labels: 🛠Refactor

#165 [Refactor] #138 : 트레이너 자격인증 화면 디자인 수정
  src/assets/images/fail.svg
  src/assets/images/success.svg
  src/components/common/ActionStateModal.vue
  src/components/common/BaseButton.vue
  src/components/common/BaseDropdown.vue
  src/components/common/BaseHeader.vue
  src/components/common/BaseInput.vue
  src/components/common/BaseStatusMessage.vue
  src/components/common/ConnectSuccessModal.vue
  src/components/trainer/certificates/CertificatesInfo.vue
  src/components/trainer/training/TrainingStep4Complete.vue
  src/views/admin/adminLoginPage.vue
  src/views/auth/LoginPage.vue
  src/views/auth/SignupPage.vue
  src/views/trainee/TraineeReviewPage.vue
  src/views/trainee/asset/AccountConnectPage.vue
  src/views/trainer/TrainerVerifyPage.vue
Labels: 🛠Refactor

#160 [Refactor] : 자산 페이지 리뉴얼
  src/assets/images/banks/hana.svg
  src/assets/images/banks/ibk.svg
  src/assets/images/banks/kookmin.svg
  src/assets/images/banks/nonghyub.svg
  src/assets/images/banks/nonghyup.svg
  src/assets/images/banks/shinhan.png
  src/assets/images/banks/woori.svg
  src/assets/images/mascot/nodata.png
  src/components/assetCharts/CompositionDonutChart.vue
  src/components/assetCharts/WithdrawalDonutChart.vue
  src/components/common/BaseHeaderWithoutBack.vue
  src/views/trainee/asset/AccountConnectPage.vue
  src/views/trainee/asset/AssetMainPage.vue
Labels: 🛠Refactor

#167 [Refactor] #156 : 트레이니 마이페이지 디자인 수정
  src/assets/images/background/background1.png
  src/assets/images/background/background2.png
  src/assets/images/background/background3.png
  src/assets/images/background/background4.png
  src/assets/images/background/background5.png
  src/assets/images/mascot/Lev100/Geumyuk_100_1.png
  src/assets/images/mascot/Lev100/Geumyuk_100_2.png
  src/assets/images/mascot/Lev100/Geumyuk_100_3.png
  src/assets/images/mascot/Lev100/Geumyuk_100_4.png
  src/assets/images/mascot/Lev100/Geumyuk_100_5.png
  src/assets/images/mascot/level/Geumyuk_1.png
  src/assets/images/mascot/level/Geumyuk_10.png
  src/assets/images/mascot/level/Geumyuk_11.png
  src/assets/images/mascot/level/Geumyuk_12.png
  src/assets/images/mascot/level/Geumyuk_13.png
  src/assets/images/mascot/level/Geumyuk_14.png
  src/assets/images/mascot/level/Geumyuk_15.png
  src/assets/images/mascot/level/Geumyuk_16.png
  src/assets/images/mascot/level/Geumyuk_17.png
  src/assets/images/mascot/level/Geumyuk_18.png
  src/assets/images/mascot/level/Geumyuk_19.png
  src/assets/images/mascot/level/Geumyuk_2.png
  src/assets/images/mascot/level/Geumyuk_20.png
  src/assets/images/mascot/level/Geumyuk_21.png
  src/assets/images/mascot/level/Geumyuk_22.png
  src/assets/images/mascot/level/Geumyuk_23.png
  src/assets/images/mascot/level/Geumyuk_24.png
  src/assets/images/mascot/level/Geumyuk_25.png
  src/assets/images/mascot/level/Geumyuk_3.png
  src/assets/images/mascot/level/Geumyuk_4.png
  src/assets/images/mascot/level/Geumyuk_5.png
  src/assets/images/mascot/level/Geumyuk_6.png
  src/assets/images/mascot/level/Geumyuk_7.png
  src/assets/images/mascot/level/Geumyuk_8.png
  src/assets/images/mascot/level/Geumyuk_9.png
  src/assets/images/mascot/logo_black.png
  src/components/layout/NavigationBar.vue
  src/components/trainee/mypage/CourseList.vue
  src/components/trainee/mypage/GrowthCard.vue
  src/components/trainee/mypage/LevelDisplay.vue
  src/components/trainee/mypage/ProfileCard.vue
  src/router/index.js
  src/views/trainee/TraineeMyPage.vue
Labels: 🛠Refactor, ✨New Feature

#175 [Refactor] #164 : 결제 로직 수정, 루틴 진행률 공유 문제 수정
  src/components/trainee/training/TraineeRoutineSection.vue
  src/stores/routineLock.js
  src/views/trainee/TraineeRoutineDetailPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
  src/views/training/TrainingDetailPage.vue
Labels: 🛠Refactor, 🐞Bug Fix

#177 [Refactor] #166: 트레이너의 트레이닝 상세 페이지 디자인 수정
  src/components/common/BaseTabNavigation.vue
  src/components/training/TrainingInfo.vue
  src/views/trainer/TrainerTrainingDetailPage.vue
Labels: 🛠Refactor

#178 [Fix] #166 : 트레이닝 상세 컨텐츠 잘리는 현상 수정
  src/components/common/BaseTabNavigation.vue
  src/components/training/TrainingInfo.vue
Labels: 🐞Bug Fix

#179 [Feature] #171 : 리뷰 컴포넌트 구현
  src/components/common/ReviewList.vue
  src/components/common/StarRating.vue
  src/views/trainer/TrainerTrainingDetailPage.vue
  src/views/training/TrainingDetailPage.vue
Labels: ✨New Feature

#181 [Refactor] 트레이니 QnA 리뉴얼
  src/assets/images/purse.png
  src/assets/images/receipt.png
  src/assets/images/shiledCheck.png
  src/components/assetCharts/BalanceLineChart.vue
  src/components/assetCharts/WithdrawalDonutChart.vue
  src/components/training/QnAList.vue
  src/composables/api/trainer/training/trainerTrainingDetailApi.js
  src/views/trainee/TraineeQnAPage.vue
  src/views/trainee/TraineeTrainingQuestionInput.vue
  src/views/trainee/asset/AccountConnectPage.vue
  src/views/trainee/asset/AssetMainPage.vue
Labels: 🛠Refactor

#182 [Refactor] #176 : 트레이니 전체 수강목록 확인 페이지 디자인 변경
  src/views/training/TrainingListPage.vue
Labels: 🛠Refactor

#185 [Feature] : 트레이너·트레이니 예약/스케줄 기능 및 UI 개선
  package-lock.json
  package.json
  src/components/chat/ChatListItem.vue
  src/components/chat/DateTimeSlotsPicker.vue
  src/components/chat/ScheduleListItem.vue
  src/composables/api/usePtApi.js
  src/router/index.js
  src/views/chat/PtChatPage.vue
  src/views/chat/PtHistoryPage.vue
  src/views/chat/PtPage.vue
  src/views/chat/TraineePtReservationPage.vue
  src/views/chat/TraineePtSchedulePage.vue
  src/views/chat/TrainerPtReservationPage.vue
  src/views/chat/TrainerPtSchedulePage.vue
  src/views/training/TrainingListPage.vue
Labels: ✨New Feature

#188 [Refactor] #187 : 트레이닝 등록 페이지 디자인 상세 수정
  src/components/common/BaseFormField.vue
  src/components/trainer/training/TrainerRoutineAddModal.vue
  src/components/trainer/training/TrainerRoutineSection.vue
  src/components/trainer/training/TrainingStep2Curriculum.vue
Labels: 🛠Refactor

#190 [Refactor] #184 : 트레이니 트레이너 화면 디자인 변경
  package-lock.json
  src/components/trainee/training/home/TrainingCard.vue
  src/composables/api/trainee/trainer/traineeTrainerApi.js
  src/composables/api/useTrainerMypageApi.js
  src/views/trainee/TraineeTrainerDetailPage.vue
  src/views/training/TrainingListPage.vue
Labels: 🛠Refactor

#191 [Refactor] : 트레이너 Q&A
  src/components/training/QnAList.vue
  src/views/trainee/TraineeQnAPage.vue
  src/views/trainer/TrainerTrainingDetailPage.vue
  src/views/training/TrainingListPage.vue
Labels: 🐞Bug Fix, ✨New Feature

#195 [Fix] : BaseTabNavigation 높이, NavigationBar PT 경로 및 예약 페이지 modal 적용
  src/components/common/BaseTabNavigation.vue
  src/components/layout/NavigationBar.vue
  src/views/chat/PtPage.vue
  src/views/chat/TraineePtReservationPage.vue
  src/views/chat/TrainerPtReservationPage.vue
Labels: ✨New Feature

#196 [Refactor] #189 : 트레이닝 상세, 루틴 수행 페이지 디자인 수정
  src/components/trainee/training/TraineeRoutineSection.vue
  src/components/trainer/training/TrainerRoutineSection.vue
  src/views/trainee/TraineeRoutineDetailPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
  src/views/training/TrainingListPage.vue
Labels: 🛠Refactor

#199 [Refactor] : 전반적인 UI 통일화 수정
  src/assets/images/trainee-icon.png
  src/assets/images/trainer-icon.png
  src/components/common/BaseHeader.vue
  src/components/common/BaseHeaderWithoutBack.vue
  src/components/common/BaseSelectRole.vue
  src/components/common/BaseStatusMessage.vue
  src/components/common/ConnectFailureModal.vue
  src/components/trainer/training/TrainerRoutineAddModal.vue
  src/router/index.js
  src/views/auth/LoginPage.vue
  src/views/auth/SignupPage.vue
  src/views/chat/PtPage.vue
  src/views/chat/TraineePtReservationPage.vue
  src/views/trainee/TraineeQnAPage.vue
  src/views/trainee/TraineeReviewPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
  src/views/trainee/TraineeTrainingQuestionInput.vue
  src/views/trainee/asset/AccountConnectPage.vue
  src/views/trainer/TrainerMyPage.vue
  src/views/trainer/TrainerReportPage.vue
  src/views/trainer/TrainerTrainingDetailPage.vue
  src/views/trainer/TrainerTrainingInputPage.vue
  src/views/trainer/TrainerTrainingPage.vue
  src/views/training/TrainingListPage.vue
  tailwind.config.js
Labels: 🛠Refactor, ✨New Feature

#203 [Refactor] #198 : 트레이니 마이페이지 디자인 수정
  src/assets/images/question_mark.png
  src/components/trainee/mypage/CollectionCard.vue
  src/components/trainee/mypage/GrowthCard.vue
  src/components/trainee/mypage/LevelDisplay.vue
  src/components/trainee/mypage/UserInfoCard.vue
  src/views/trainee/TraineeMyPage.vue
Labels: 🛠Refactor, ✨New Feature

#201 [Refactor] #200 : 수익 관리 페이지 디자인 수정
  src/components/layout/NavigationBar.vue
  src/views/trainer/TrainerReportPage.vue
Labels: 🛠Refactor

#216 [Refactor] #212 : 트레이너 마이페이지 수정
  .github/workflows/main.yml
  Dockerfile
  docker-compose.yml
  src/views/trainer/TrainerMyPage.vue
Labels: 🛠Refactor

#219 [Refactor] #214 : 리뷰 입력 컴포넌트 변경, 트레이닝 검색 시 없을 때 문구 추가
  src/components/trainer/training/TrainerRoutineAddModal.vue
  src/views/trainee/TraineeReviewPage.vue
  src/views/trainer/TrainerTrainingInputPage.vue
  src/views/training/TrainingListPage.vue
Labels: 🛠Refactor

#220 [Refactor] #211 : 모달 창 디자인 변경
  src/components/common/PaymentModal.vue
  src/components/trainee/training/RoutineResultModal.vue
  src/views/trainee/TraineeRoutineDetailPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
  src/views/training/TrainingDetailPage.vue
Labels: 🛠Refactor

#225 [Refactor] : 채팅창 관련 UI 개선
  src/assets/images/mascot/profile.png
  src/components/chat/ChatBubble.vue
  src/components/chat/ChatHeader.vue
  src/views/chat/PtChatPage.vue
  src/views/chat/PtHistoryPage.vue
  src/views/chat/TraineePtSchedulePage.vue
  src/views/chat/TrainerPtSchedulePage.vue
  src/views/trainee/asset/AssetAiChatPage.vue
  src/views/training/TrainingListPage.vue
Labels: 🛠Refactor

#228 [Refactor] #227 : baseformfield 수정, 주관식 답안 추가
  src/components/common/BaseFormField.vue
  src/components/trainer/training/TrainerRoutineAddModal.vue
Labels: 🛠Refactor

#229 [Refactor] # 226 : 트레이닝 상세 페이지 리뷰 관련 수정 완료
  src/views/trainee/TraineeReviewPage.vue
  src/views/trainee/TraineeTrainingDetailPage.vue
Labels: 🛠Refactor

#223 [Refactor] : 자격인증 화면 디자인 수정
  src/views/trainer/TrainerTrainingDetailPage.vue
  src/views/trainer/TrainerTrainingInputPage.vue
  src/views/trainer/TrainerVerifyPage.vue
Labels: 🛠Refactor

#249 [Fix] #248 : 금육이 이미지 임포트 방식 변경
  src/components/trainee/mypage/LevelDisplay.vue
Labels: 🐞Bug Fix

#252 [Fix] #251 : 금육이 수집 리스트 이미지 불러오기 수정
  src/components/trainee/mypage/CollectionCard.vue
Labels: 🐞Bug Fix
